### ISSUE TITLE
GPU metadata for your card does not exist (5070 Ti)

### ISSUE THREAD

**Issue by crafty35a** [ElPumpo/TinyNvidiaUpdateChecker#247]
I've been unable to use this tool since installing my 5070 Ti, here is the error:

![Image](https://github.com/user-attachments/assets/f524ad34-909d-444c-b9e1-40a4497d502d)

**Comment by ElPumpo** [comment]
Hi, nice GPU you bought.

The data repo we use has not been updated yet to support your GPU.

Refer to https://github.com/ZenitH-AT/nvidia-data/issues/5

**Comment by ElPumpo** [comment]
OK should be fixed now

**Comment by crafty35a** [comment]
Is there something I need to do on my end to get this working? Or is a client update to the tool required? I'm still getting the same error with 1.19.1

**Comment by ElPumpo** [comment]
Good, but this issue needs to stay open, it has to be fixed.

I will investigate

**Comment by ElPumpo** [comment]
Okay ive fixed this caching bug in the latest update
